version: '3'

services:
  JETMailerDB:
    image: mysql:5.7
    container_name: JETMailerMySQL
    environment:
      MYSQL_ROOT_PASSWORD: A123654Z
      MYSQL_DATABASE: laravel
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
  JETMailerWeb:
    image: php:7.3
    container_name: JETMailerPHP
    depends_on:
      - JETMailerDB
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
